///*
// * 7SEGMENT_Module.c
// *
// *  Created on: Sep 11, 2018
// *      Author: zsolt.balo
// */
//
//#include "SEVEN_SEGMENT_Module_Cfg.h"
//
//static uint8 SEVEN_SEGMENT_Module_Patterns[25] =
//{
//	/*0*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F,
//	/*1*/
//	SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C,
//	/*2*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_G,
//	/*3*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_G,
//	/*4*/
//	SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_F|SEVEN_SEGMENT_LED_G,
//	/*5*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_F|SEVEN_SEGMENT_LED_G,
//	/*6*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F|SEVEN_SEGMENT_LED_G,
//	/*7*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C,
//	/*8*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F|SEVEN_SEGMENT_LED_G,
//	/*9*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_F|SEVEN_SEGMENT_LED_G,
//	/*A*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F|SEVEN_SEGMENT_LED_G,
//	/*B*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F|SEVEN_SEGMENT_LED_G,
//	/*C*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F,
//	/*E*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F|SEVEN_SEGMENT_LED_G,
//	/*F*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F|SEVEN_SEGMENT_LED_G,
//	/*G*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F|SEVEN_SEGMENT_LED_G,
//	/*H*/
//	SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F|SEVEN_SEGMENT_LED_G,
//	/*I*/
//	SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C,
//	/*J*/
//	SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_E,
//	/*L*/
//	SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F,
//	/*O*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F,
//	/*P*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F|SEVEN_SEGMENT_LED_G,
//	/*S*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_F|SEVEN_SEGMENT_LED_G,
//	/*U*/
//	SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_C|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_F,
//	/*Z*/
//	SEVEN_SEGMENT_LED_A|SEVEN_SEGMENT_LED_B|SEVEN_SEGMENT_LED_D|SEVEN_SEGMENT_LED_E|SEVEN_SEGMENT_LED_G
//};
//
//void SEVEN_SEGMENT_Module_Update_Display(uint8 Seven_Segment_setup_Nr,uint8 Characther)
//{
//	uint8 Slected_Character = SEVEN_SEGMENT_Module_Patterns[Characther];
//
//	SEVEN_SEGMENT_Module_Clear(Seven_Segment_setup_Nr);
//
//	#if(SEVEN_SEGMENT_MODULE_INTERFACE == SEVEN_SEGMENT_MODULE_GPIO_INTERFACE)
//
//		if((Slected_Character & (0x01<<0x00))!=0x00)
//		{
//			LED_Module_Set_On(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_A_Indicator);
//		}
//		if((Slected_Character & (0x01<<0x01))!=0x00)
//		{
//			LED_Module_Set_On(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_B_Indicator);
//		}
//		if((Slected_Character & (0x01<<0x02))!=0x00)
//		{
//			LED_Module_Set_On(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_C_Indicator);
//		}
//		if((Slected_Character & (0x01<<0x03))!=0x00)
//		{
//			LED_Module_Set_On(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_D_Indicator);
//		}
//		if((Slected_Character & (0x01<<0x04))!=0x00)
//		{
//			LED_Module_Set_On(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_E_Indicator);
//		}
//		if((Slected_Character & (0x01<<0x05))!=0x00)
//		{
//			LED_Module_Set_On(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_F_Indicator);
//		}
//		if((Slected_Character & (0x01<<0x06))!=0x00)
//		{
//			LED_Module_Set_On(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_G_Indicator);
//		}
//		if((Slected_Character & (0x01<<0x07))!=0x00)
//		{
//			LED_Module_Set_On(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_POINT_Indicator);
//		}
//	#endif
//		SHIFT_REGISTER_Module_Update(SEVEN_SEGMENT_SR_SETUP[Seven_Segment_setup_Nr].SHIFT_REGISTER_INSTANCE,Slected_Character);
//}
//
//void SEVEN_SEGMENT_Module_Clear(uint8 Seven_Segment_setup_Nr)
//{
//	#if(SEVEN_SEGMENT_MODULE_INTERFACE == SEVEN_SEGMENT_MODULE_GPIO_INTERFACE)
//
//		LED_Module_Set_Off(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_A_Indicator);
//		LED_Module_Set_Off(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_B_Indicator);
//		LED_Module_Set_Off(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_C_Indicator);
//		LED_Module_Set_Off(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_D_Indicator);
//		LED_Module_Set_Off(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_E_Indicator);
//		LED_Module_Set_Off(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_F_Indicator);
//		LED_Module_Set_Off(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_G_Indicator);
//		LED_Module_Set_Off(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr].LEVEL_POINT_Indicator);
//
//	#endif
//		SHIFT_REGISTER_Module_Clear(SEVEN_SEGMENT_SR_SETUP[Seven_Segment_setup_Nr].SHIFT_REGISTER_INSTANCE);
//}
//
//#if(SEVEN_SEGMENT_MODULE_INTERFACE == SEVEN_SEGMENT_MODULE_GPIO_INTERFACE)
//
//	void SEVEN_SEGMENT_Module_Set_Dimming(uint8 Seven_Segment_setup_Nr,uint8 DutyCycle)
//	{
///*		LED_Module_Set_Dimming(SEVEN_SEGMENT_SETUP[Seven_Segment_setup_Nr],DutyCycle);*/
//	}
//
//#else
//
//	void SEVEN_SEGMENT_Module_Set_Dimming(uint8 Seven_Segment_setup_Nr,uint8 DutyCycle)
//	{
//		/*When using SPI dimming is not available*/
//	}
//#endif
