///*
// * 7SEGMENT_Module_Cfg.c
// *
// *  Created on: Sep 11, 2018
// *      Author: zsolt.balo
// */
//
//#include "SEVEN_SEGMENT_Module_Cfg.h"
//
//#if(SEVEN_SEGMENT_MODULE_INTERFACE == SEVEN_SEGMENT_MODULE_GPIO_INTERFACE)
//
//	static SEVEN_SEGMENT_Module_Setup_Type SEVEN_SEGMENT_CONF_SETUP[SEVEN_SEGMENT_MODULE_INSTANCE_NUM];
//
//	SEVEN_SEGMENT_Module_Setup_Type* SEVEN_SEGMENT_SETUP = SEVEN_SEGMENT_CONF_SETUP;
//
//#endif
//
//#if(SEVEN_SEGMENT_MODULE_INTERFACE == SEVEN_SEGMENT_MODULE_SHIFT_REGISTER_INTERFACE)
//
//	static SEVEN_SEGMENT_Module_Shift_Register_Instance  SEVEN_SEGMENT_SR_CONF_SETUP[SEVEN_SEGMENT_MODULE_INSTANCE_NUM];
//
//	SEVEN_SEGMENT_Module_Shift_Register_Instance* SEVEN_SEGMENT_SR_SETUP = SEVEN_SEGMENT_SR_CONF_SETUP;
//
//#endif
//
//void SEVEN_SEGMENT_Module_Init_Cfg()
//{
//	#if(SEVEN_SEGMENT_MODULE_INTERFACE == SEVEN_SEGMENT_MODULE_GPIO_INTERFACE)
//
//		LED_Module_Init_Cfg();
//
//		SEVEN_SEGMENT_CONF_SETUP[SEVEN_SEGMENT_MODULE_0].LEVEL_A_Indicator 		= LED_MODULE_0;
//		SEVEN_SEGMENT_CONF_SETUP[SEVEN_SEGMENT_MODULE_0].LEVEL_B_Indicator 		= LED_MODULE_1;
//		SEVEN_SEGMENT_CONF_SETUP[SEVEN_SEGMENT_MODULE_0].LEVEL_C_Indicator 		= LED_MODULE_2;
//		SEVEN_SEGMENT_CONF_SETUP[SEVEN_SEGMENT_MODULE_0].LEVEL_D_Indicator 		= LED_MODULE_3;
//		SEVEN_SEGMENT_CONF_SETUP[SEVEN_SEGMENT_MODULE_0].LEVEL_E_Indicator 		= LED_MODULE_4;
//		SEVEN_SEGMENT_CONF_SETUP[SEVEN_SEGMENT_MODULE_0].LEVEL_F_Indicator 		= LED_MODULE_5;
//		SEVEN_SEGMENT_CONF_SETUP[SEVEN_SEGMENT_MODULE_0].LEVEL_G_Indicator 		= LED_MODULE_6;
//		SEVEN_SEGMENT_CONF_SETUP[SEVEN_SEGMENT_MODULE_0].LEVEL_POINT_Indicator 	= LED_MODULE_7;
//
//	#endif
//
//	#if(SEVEN_SEGMENT_MODULE_INTERFACE == SEVEN_SEGMENT_MODULE_SHIFT_REGISTER_INTERFACE)
//
//		SHIFT_REGISTER_Module_Init_Cfg();
//		SEVEN_SEGMENT_SR_CONF_SETUP[SEVEN_SEGMENT_MODULE_0].SHIFT_REGISTER_INSTANCE = SHIFT_REGISTER_MODULE_0;
//
//	#endif
//
//}
