/*
 * USART_Driver_Cfg.c
 *
 *  Created on: Oct 23, 2018
 *      Author: zsolt.balo
 */

#include "USART_Driver_Cfg.h"

USART_Driver_Setup_Type USART_CONF_SETUP[USART_DRIVER_INSTANCE_NUM]=
{
	{
		USART1,
		9600,
		USART_DRIVER_8_DATA_BITS,
		USART_DRIVER_PARITY_CONTROLL_DISABLE,
		DEFAULT,
		USART_DRIVER_TX_ENABLE,
		USART_DRIVER_RX_ENABLE,
		USART_DRIVER_1_STOP_BIT,
		USART_DRIVER_HALF_DUPLEX_DISABLE,
		USART_DRIVER_OVER16,
	}
};

USART_Driver_Setup_Type* USART_SETUP = USART_CONF_SETUP;

