/*
 * LEVEL_INDICATOR_Module_Cfg.h
 *
 *  Created on: Sep 10, 2018
 *      Author: zsolt.balo
 */

#ifndef MODULES_HARDWARE_MODULES_LED_MODULE_LEVEL_INDICATOR_MODULE_LEVEL_INDICATOR_MODULE_CFG_H_
#define MODULES_HARDWARE_MODULES_LED_MODULE_LEVEL_INDICATOR_MODULE_LEVEL_INDICATOR_MODULE_CFG_H_

#include "LEVEL_INDICATOR_Module.h"

#define LEVEL_INDICATOR_MODULE_INTERFACE 							LEVEL_INDICATOR_MODULE_GPIO_INTERFACE
#define LEVEL_INDICATOR_MODULE_INSTANCE_NUM 						((uint32)0x01)

typedef enum
{
	LEVEL_INDICATOR_MODULE_0
}
LEVEL_INDICATOR_Module_Instances;

#endif /* MODULES_HARDWARE_MODULES_LED_MODULE_LEVEL_INDICATOR_MODULE_LEVEL_INDICATOR_MODULE_CFG_H_ */
