/*
 * NVIC_Driver_Cfg.h
 *
 *  Created on: Apr 20, 2018
 *      Author: zsolt.balo
 */

#ifndef DRIVERS_NVIC_DRIVER_NVIC_DRIVER_CFG_H_
#define DRIVERS_NVIC_DRIVER_NVIC_DRIVER_CFG_H_

#include "NVIC_Driver.h"

#define NVIC_DRIVER_TIMER_INTERRUPT_ENABLE					NOK
#define NVIC_DRIVER_EXTI_INTERRUPT_ENABLE					OK
#define NVIC_DRIVER_SYSTICK_INTERRUPT_ENABLE				OK
#define NVIC_DRIVER_RTC_INTERRUPT_ENABLE					NOK
#define NVIC_DRIVER_WWDT_INTERRUPT_ENABLE					NOK

#if (NVIC_DRIVER_EXTI_INTERRUPT_ENABLE	== OK)
	#include "EXTI_Driver_Cfg.h"

	#if (EXTI_DRIVER_INTERRUPT_0_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_0_FLAG						OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_1_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_1_FLAG						OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_2_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_2_FLAG						OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_3_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_2_FLAG						OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_4_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_4_FLAG						OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_5_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_5_FLAG						OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_6_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_6_FLAG						OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_7_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_7_FLAG						OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_8_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_8_FLAG						OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_9_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_9_FLAG						OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_10_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_10_FLAG					OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_11_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_11_FLAG					OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_12_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_12_FLAG					OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_13_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_13_FLAG					OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_14_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_14_FLAG					OK
	#endif

	#if (EXTI_DRIVER_INTERRUPT_15_ENABLE==OK)
		#define NVIC_DRIVER_EXTI_15_FLAG					OK
	#endif

#endif

#if (NVIC_DRIVER_RTC_INTERRUPT_ENABLE == OK)
	#include "RTC_Driver_Cfg.h"

	#if(RTC_DRIVER_SELECTED_INTERRUPT == RTC_DRIVER_OVERFLOW_INTERRUPT_ENABLE)
		#define NVIC_RTC_OVERFLOW_INTERRUPT_FLAG 			OK
	#endif

	#if(RTC_DRIVER_SELECTED_INTERRUPT == RTC_DRIVER_ALARM_INTERRUPT_ENABLE)
		#define NVIC_RTC_ALARM_INTERRUPT_FLAG				OK
	#endif

	#if(RTC_DRIVER_SELECTED_INTERRUPT == RTC_DRIVER_SECOND_INTERRUPT_ENABLE)
		#define NVIC_RTC_SECOND_INTERRUPT_FLAG				OK
	#endif

#endif

#endif /* DRIVERS_NVIC_DRIVER_NVIC_DRIVER_CFG_H_ */
