/*
 * LED_Module_Cfg.c
 *
 *  Created on: Sep 5, 2018
 *      Author: zsolt.balo
 */

#include "LED_Module_Cfg.h"

static LED_Module_Setup_Type LED_CONF_SETUP[LED_MODULE_INSTANCE_NUM];

LED_Module_Setup_Type* LED_SETUP = LED_CONF_SETUP;

void LED_Module_Init_Cfg()
{
/*
	LED_CONF_SETUP[LED_MODULE_0].GPIO_Instance_Nr = GPIO_DRIVER_PORTA;
	LED_CONF_SETUP[LED_MODULE_0].GPIO_Pin_Nr = GPIO_SETUP[GPIO_DRIVER_PORTA].GPIO_Pins[GPIO_DRIVER_PORTA_PIN1];

	LED_CONF_SETUP[LED_MODULE_1].GPIO_Instance_Nr = GPIO_DRIVER_PORTA;
	LED_CONF_SETUP[LED_MODULE_1].GPIO_Pin_Nr = GPIO_SETUP[GPIO_DRIVER_PORTA].GPIO_Pins[GPIO_DRIVER_PORTA_PIN2];

	LED_CONF_SETUP[LED_MODULE_2].GPIO_Instance_Nr = GPIO_DRIVER_PORTA;
	LED_CONF_SETUP[LED_MODULE_2].GPIO_Pin_Nr = GPIO_SETUP[GPIO_DRIVER_PORTA].GPIO_Pins[GPIO_DRIVER_PORTA_PIN3];

	LED_CONF_SETUP[LED_MODULE_3].GPIO_Instance_Nr = GPIO_DRIVER_PORTA;
	LED_CONF_SETUP[LED_MODULE_3].GPIO_Pin_Nr = GPIO_SETUP[GPIO_DRIVER_PORTA].GPIO_Pins[GPIO_DRIVER_PORTA_PIN4];

	LED_CONF_SETUP[LED_MODULE_4].GPIO_Instance_Nr = GPIO_DRIVER_PORTA;
	LED_CONF_SETUP[LED_MODULE_4].GPIO_Pin_Nr = GPIO_SETUP[GPIO_DRIVER_PORTA].GPIO_Pins[GPIO_DRIVER_PORTA_PIN5];

	LED_CONF_SETUP[LED_MODULE_5].GPIO_Instance_Nr = GPIO_DRIVER_PORTA;
	LED_CONF_SETUP[LED_MODULE_5].GPIO_Pin_Nr = GPIO_SETUP[GPIO_DRIVER_PORTA].GPIO_Pins[GPIO_DRIVER_PORTA_PIN6];

	LED_CONF_SETUP[LED_MODULE_6].GPIO_Instance_Nr = GPIO_DRIVER_PORTA;
	LED_CONF_SETUP[LED_MODULE_6].GPIO_Pin_Nr = GPIO_SETUP[GPIO_DRIVER_PORTA].GPIO_Pins[GPIO_DRIVER_PORTA_PIN7];

	LED_CONF_SETUP[LED_MODULE_7].GPIO_Instance_Nr = GPIO_DRIVER_PORTA;
	LED_CONF_SETUP[LED_MODULE_7].GPIO_Pin_Nr = GPIO_SETUP[GPIO_DRIVER_PORTA].GPIO_Pins[GPIO_DRIVER_PORTA_PIN8];

	LED_CONF_SETUP[LED_MODULE_8].GPIO_Instance_Nr = GPIO_DRIVER_PORTB;
	LED_CONF_SETUP[LED_MODULE_8].GPIO_Pin_Nr = GPIO_SETUP[GPIO_DRIVER_PORTB].GPIO_Pins[GPIO_DRIVER_PORTB_PIN0];

	LED_CONF_SETUP[LED_MODULE_9].GPIO_Instance_Nr = GPIO_DRIVER_PORTB;
	LED_CONF_SETUP[LED_MODULE_9].GPIO_Pin_Nr = GPIO_SETUP[GPIO_DRIVER_PORTB].GPIO_Pins[GPIO_DRIVER_PORTB_PIN1];
*/


}

