/*
 * HWENCODER_Driver_Cfg.h
 *
 *  Created on: 19 feb. 2018
 *      Author: Zsole
 */

#ifndef HWENCODER_DRIVER_CFG_H_
#define HWENCODER_DRIVER_CFG_H_

#include "HWENCODER_Driver.h"

#define HWENCODER_DRIVER_SELECTED_TIMER_INPUT					HWENCODER_DRIVER_COUNT_ON_TIMER_INPUT_1_AND_2
#define HWENCODER_DRIVER_SELECTED_POLARITY_TIMER_INPUT_1		HWENCODER_DRIVER_NONINVERTED_POLARITY_RISING_EDGE
#define HWENCODER_DRIVER_SELECTED_POLARITY_TIMER_INPUT_2		HWENCODER_DRIVER_NONINVERTED_POLARITY_RISING_EDGE

#endif /* HWENCODER_DRIVER_CFG_H_ */
