/*
 * HWENCODER_Driver_Cfg.h
 *
 *  Created on: 19 feb. 2018
 *      Author: Zsole
 */

#include "HWENCODER_Driver_Cfg.h"

HWENCODER_Driver_Setup_Type HWENCODER_CONF_SETUP[HWENCODER_DRIVER_INSTANCE_NUM]=
{
	{
			TIM4,
			HWENCODER_DRIVER_COUNT_ON_TIMER_INPUT_1_AND_2,
			HWENCODER_DRIVER_CHANNEL_1_AND_2,
			HWENCODER_DRIVER_CAPTURE_COMPARE_OUTPUT_ENABLE_PRIMARY|
			HWENCODER_DRIVER_CAPTURE_COMPARE_OUTPUT_ENABLE_SECONDARY|
			HWENCODER_DRIVER_CAPTURE_COMPARE_OUTPUT_DISABLE_THIRD|
			HWENCODER_DRIVER_CAPTURE_COMPARE_OUTPUT_DISABLE_FOURTH,
			HWENCODER_DRIVER_CAPTURE_COMPARE_SELECTION_PRIMARY_ON_TI1,
			HWENCODER_DRIVER_CAPTURE_COMPARE_SELECTION_SECONDARY_ON_TI2
	},
};

HWENCODER_Driver_Setup_Type* HWENCODER_SETUP = HWENCODER_CONF_SETUP;
