/*
 * DMA_Driver_Cfg.h
 *
 *  Created on: Aug 14, 2018
 *      Author: zsolt.balo
 */

#ifndef DRIVERS_DMA_DRIVER_DMA_DRIVER_CFG_H_
#define DRIVERS_DMA_DRIVER_DMA_DRIVER_CFG_H_

#include "DMA_Driver.h"

#define DMA_DRIVER_RUNNING_MODE						DMA_DRIVER_NORMAL_MODE
#define DMA_DRIVER_MEMMORY_TO_MEMMORY_FUNCTIONALITY OK
#define DMA_DRIVER_CHANNEL_PRIORITY					DMA_DRIVER_CHANNEL_PRIORITY_MEDIUM
#define DMA_DRIVER_MEMMORY_SIZE						DMA_DRIVER_MEMMORY_SIZE_32_BITS
#define DMA_PERIPHERAL_SIZE							DMA_PERIPHERAL_SIZE_8_bits
#define DMA_DRIVER_MEMMORY_INCREMENT 				OK
#define DMA_DRIVER_PERIPHERAL_INCREMENT 			NOK
#define DMA_DRIVER_DIRECTION						DMA_DRIVER_DIRECTION_FROM_PERIPHERAL

#endif /* DRIVERS_DMA_DRIVER_DMA_DRIVER_CFG_H_ */
