/*
 * NOKIA_5110_LCD_Driver_Cfg.h
 *
 *  Created on: May 21, 2018
 *      Author: zsolt.balo
 */

#ifndef DRIVERS_MODULES_NOKIA_5110_LCD_MODULE_NOKIA_5110_LCD_DRIVER_CFG_H_
#define DRIVERS_MODULES_NOKIA_5110_LCD_MODULE_NOKIA_5110_LCD_DRIVER_CFG_H_

#include "NOKIA_5110_LCD_Driver.h"

#define NOKIA_5110_DRIVER_LCD_NUMBER_LEN_THOUSANDS				NOK
#define NOKIA_5110_DRIVER_LCD_NUMBER_LEN_HUNDREDS				OK
#define NOKIA_5110_DRIVER_LCD_NUMBER_LEN_TENS					OK

#endif /* DRIVERS_MODULES_NOKIA_5110_LCD_MODULE_NOKIA_5110_LCD_DRIVER_CFG_H_ */
