/*
 * BUTTON_Module_Cfg.h
 *
 *  Created on: Sep 11, 2018
 *      Author: zsolt.balo
 */

#ifndef MODULES_HARDWARE_MODULES_BUTTON_MODULE_BUTTON_MODULE_CFG_H_
#define MODULES_HARDWARE_MODULES_BUTTON_MODULE_BUTTON_MODULE_CFG_H_

#include "BUTTON_Module.h"

#define BUTTON_MODULE_INSTANCE_NUM 					((uint32)0x01)

typedef enum
{
	BUTTON_MODULE_0
}
BUTTON_Module_Instances;

#endif /* MODULES_HARDWARE_MODULES_BUTTON_MODULE_BUTTON_MODULE_CFG_H_ */
