/*
 * EXTI_Driver_Cfg.h
 *
 *  Created on: Feb 6, 2018
 *      Author: zsolt.balo
 */

#ifndef EXTI_DRIVER_CFG_H_
#define EXTI_DRIVER_CFG_H_

#include "EXTI_Driver.h"

#define EXTI_DRIVER_INTERRUPT_MODE						OK
#define EXTI_DRIVER_EVENT_MODE							OK
#define EXTI_DRIVER_INTERRUPT_0_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_1_ENABLE					OK
#define EXTI_DRIVER_INTERRUPT_2_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_3_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_4_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_5_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_6_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_7_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_8_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_9_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_10_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_11_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_12_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_13_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_14_ENABLE					NOK
#define EXTI_DRIVER_INTERRUPT_15_ENABLE					NOK

#endif /* EXTI_DRIVER_CFG_H_ */
