/*
 * SYSTEM_Driver_Cfg.h
 *
 *  Created on: Oct 1, 2018
 *      Author: zsolt.balo
 */

#ifndef DRIVERS_SYSTEM_DRIVER_SYSTEM_DRIVER_CFG_H_
#define DRIVERS_SYSTEM_DRIVER_SYSTEM_DRIVER_CFG_H_

#include "SYSTEM_Driver.h"

#define SYSTEM_DRIVER_CLK_SOURCE 		SYSTEM_DRIVER_SWITCH_TO_PLL
#define SYSTEM_DRIVER_PLL_SOURCE 		SYSTEM_DRIVER_PLL_CLOCK_SRC_HSE
#define SYSTEM_DRIVER_PLL_MULTIPLIER 	SYSTEM_DRIVER_PLLMUL_9
#define SYSTEM_DRIVER_HCLK_DIV 	 		SYSTEM_DRIVER_AHB_NDIV
#define SYSTEM_DRIVER_PCLK1_DIV 		SYSTEM_DRIVER_APB1_DIV2
#define SYSTEM_DRIVER_PCLK2_DIV 		SYSTEM_DRIVER_APB2_NDIV

#endif /* DRIVERS_SYSTEM_DRIVER_SYSTEM_DRIVER_CFG_H_ */
