/*
 * TWI_Driver_Cfg.h
 *
 *  Created on: Jul 17, 2018
 *      Author: zsolt.balo
 */

#ifndef DRIVERS_TWI_DRIVER_TWI_DRIVER_CFG_H_
#define DRIVERS_TWI_DRIVER_TWI_DRIVER_CFG_H_

#include "TWI_Driver.h"

#define TWI_DRIVER_TWI1								OK
#define TWI_DRIVER_TWI2								NOK

#define TWI_DRIVER_FUNCTIONALITY					TWI_DRIVER_POLLING_FUNCTIONALITY
#define TWI_DRIVER_ADDRESSING_MODE					NOK
#define TWI_DRIVER_DUALADDRESSING					NOK
#define TWI_DRIVER_OWNADDRESS1						0x0F
#define TWI_DRIVER_OWNADDRESS2						0x00
#define TWI_DRIVER_ACKNOWLEDGE_ENABLE				OK
#define TWI_DRIVER_CLOCK_STRETCHING_DISABLE			NOK
#define TWI_DRIVER_GENERAL_CALL_ENABLE				NOK
#define TWI_DRIVER_CLOCK_MODE						TWI_DRIVER_STANDARD_SPEED_100KHz
#define TWI_DRIVER_FAST_MODE_DUTY_CYCLE				TWI_DRIVER_FAST_SPEED_DUTY_CYCLE_2
#define TWI_DRIVER_CLOCK_FREQUENCY					100000
#define TWI_DRIVER_SMB_BUS_MODE						NOK

#endif /* DRIVERS_TWI_DRIVER_TWI_DRIVER_CFG_H_ */
