/*
 * ADC_Driver_Cfg.c
 *
 *  Created on: Sep 12, 2018
 *      Author: zsolt.balo
 */

#include "ADC_Driver_Cfg.h"

ADC_Driver_Setup_Type ADC_CONF_SETUP[ADC_DRIVER_INSTANCE_NUM]=
{
	{
		ADC1,
		OK,
		NOK,
		OK,
		ADC_ALIGNMENT_RIGHT,
		#if(ADC_DRIVER_SEQUENTIAL_READ == OK)
			ADC_DRIVER_SEQUENCE_2_CONVERSIONS,
		#else
			ADC_DRIVER_SEQUENCE_1_CONVERSIONS,
		#endif
		0x02,
		{ADC_DRIVER_CHANNEL_1,ADC_DRIVER_CHANNEL_2},
		{ADC_DRIVER_CHANNEL_SAMPLING_TIME_55_5_CYCLES,ADC_DRIVER_CHANNEL_SAMPLING_TIME_55_5_CYCLES},
		{ADC_DRIVER_SEQUENCE_POSITION_1,ADC_DRIVER_SEQUENCE_POSITION_2}
	}
};

ADC_Driver_Setup_Type* ADC_SETUP = ADC_CONF_SETUP;
