/*
 * SHIFT_REGISTER_Module_Cfg.h
 *
 *  Created on: Sep 18, 2018
 *      Author: zsolt.balo
 */

#ifndef MODULES_HARDWARE_MODULES_SHIFT_REGISTER_MODULE_SHIFT_REGISTER_MODULE_CFG_H_
#define MODULES_HARDWARE_MODULES_SHIFT_REGISTER_MODULE_SHIFT_REGISTER_MODULE_CFG_H_

#include "SHIFT_REGISTER_Module.h"

#define SHIFT_REGISTER_INSTANCE_NUM 					((uint32)0x01)

typedef enum
{
	SHIFT_REGISTER_MODULE_0
}
SHIFT_REGISTER_Module_Instances;

#endif /* MODULES_HARDWARE_MODULES_SHIFT_REGISTER_MODULE_SHIFT_REGISTER_MODULE_CFG_H_ */
