/*
 * GPIO_Driver_Cfg.h
 *
 *  Created on: Jan 23, 2018
 *      Author: zsolt.balo
 */
#ifndef GPIO_DRIVER_CFG_H_
#define GPIO_DRIVER_CFG_H_

#include "GPIO_Driver.h"

#define GPIO_DRIVER_GPIOA 				  			OK
#define GPIO_DRIVER_GPIOB 				  			OK
#define GPIO_DRIVER_GPIOC 				  			OK
#define GPIO_DRIVER_GPIOD 				  			OK
#define GPIO_DRIVER_GPIOE 				  			OK
#define GPIO_DRIVER_GPIOF 				  			OK
#define GPIO_DRIVER_GPIOG 				  			OK
#define GPIO_DRIVER_GPIOH 				  			NOK
#define GPIO_DRIVER_GPIOI 				  			NOK
#define GPIO_DRIVER_GPIOJ 				  			NOK
#define GPIO_DRIVER_GPIOK 				  			NOK
#define GPIO_DRIVER_INSTANCE_NUM 					((uint32)0x06)

typedef enum
{
	GPIO_DRIVER_PORTB,
	GPIO_DRIVER_PORTC,
	GPIO_DRIVER_PORTD,
	GPIO_DRIVER_PORTE,
	GPIO_DRIVER_PORTF,
	GPIO_DRIVER_PORTG
}GPIO_Driver_Port_Instances;

typedef enum
{
	/*PORT B Pins*/
	GPIO_DRIVER_PORTB_PIN5,
	GPIO_DRIVER_PORTB_PIN6,

	/*PORT C Pins*/
	GPIO_DRIVER_PORTC_PIN0,

	/*PORT D Pins*/
	GPIO_DRIVER_PORTD_PIN0,
	GPIO_DRIVER_PORTD_PIN1,
	GPIO_DRIVER_PORTD_PIN8,
	GPIO_DRIVER_PORTD_PIN9,
	GPIO_DRIVER_PORTD_PIN10,
	GPIO_DRIVER_PORTD_PIN14,
	GPIO_DRIVER_PORTD_PIN15,

	/*PORT E Pins*/
	GPIO_DRIVER_PORTE_PIN_0,
	GPIO_DRIVER_PORTE_PIN_1,
	GPIO_DRIVER_PORTE_PIN_7,
	GPIO_DRIVER_PORTE_PIN_8,
	GPIO_DRIVER_PORTE_PIN_9,
	GPIO_DRIVER_PORTE_PIN_10,
	GPIO_DRIVER_PORTE_PIN_11,
	GPIO_DRIVER_PORTE_PIN_12,
	GPIO_DRIVER_PORTE_PIN_13,
	GPIO_DRIVER_PORTE_PIN_14,
	GPIO_DRIVER_PORTE_PIN_15,

	/*PORT F Pins*/
	GPIO_DRIVER_PORTF_PIN_0,
	GPIO_DRIVER_PORTF_PIN_1,
	GPIO_DRIVER_PORTF_PIN_2,
	GPIO_DRIVER_PORTF_PIN_3,
	GPIO_DRIVER_PORTF_PIN_4,
	GPIO_DRIVER_PORTF_PIN_5,
	GPIO_DRIVER_PORTF_PIN_11,
	GPIO_DRIVER_PORTF_PIN_12,
	GPIO_DRIVER_PORTF_PIN_13,
	GPIO_DRIVER_PORTF_PIN_14,
	GPIO_DRIVER_PORTF_PIN_15,

	/*PORT G Pins*/
	GPIO_DRIVER_PORTG_PIN_0,
	GPIO_DRIVER_PORTG_PIN_1,
	GPIO_DRIVER_PORTG_PIN_4,
	GPIO_DRIVER_PORTG_PIN_5,
	GPIO_DRIVER_PORTG_PIN_8,
	GPIO_DRIVER_PORTG_PIN_15
}GPIO_Driver_Pin_Instances;

#endif /* GPIO_DRIVER_CFG_STM32F103_H_ */
