/*
 * GPIO_Driver_Cfg.c
 *
 *  Created on: Aug 21, 2018
 *      Author: zsolt.balo
 */

#include "GPIO_Driver_Cfg.h"

GPIO_Driver_Setup_Type GPIO_CONF_SETUP[GPIO_DRIVER_INSTANCE_NUM]=
{
	{
			GPIOB,
			0x02,
			{0x05,0x06},
			{GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF},
			{GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP},
			{GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH},
			{GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD},
			{GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12}
	},
	{
			GPIOC,
			0x01,
			{0x00},
			{GPIO_DRIVER_MODE_AF},
			{GPIO_DRIVER_OUT_TYPE_PP},
			{GPIO_DRIVER_SPEED_HIGH},
			{GPIO_DRIVER_PUPD_NO_PUPD},
			{GPIO_DRIVER_AF_OPT_12}
	},
	{
			GPIOD,
			0x07,
			{
				0x00, 0x01, 0x08,
				0x09, 0x0A, 0x0E,
				0x0F
			},
			{
					GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,
					GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,
					GPIO_DRIVER_MODE_AF
			},
			{
					GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,
					GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,
					GPIO_DRIVER_OUT_TYPE_PP
			},
			{
					GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,
					GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,
					GPIO_DRIVER_SPEED_HIGH
			},
			{
					GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,
					GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,
					GPIO_DRIVER_PUPD_NO_PUPD
			},
			{
					GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,
					GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,
					GPIO_DRIVER_AF_OPT_12
			}
	},
	{
			GPIOE,
			0x0B,
			{
					0x00, 0x01, 0x07,
					0x08, 0x09, 0x0A,
					0x0B, 0x0C, 0x0D,
					0x0E, 0x0F
			},
			{
					GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,
					GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,
					GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,
					GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF
			},
			{
					GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,
					GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,
					GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,
					GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP
			},
			{
					GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,
					GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,
					GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,
					GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH
			},
			{
					GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,
					GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,
					GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,
					GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD
			},
			{
					GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,
					GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,
					GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,
					GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12
			}
	},
	{
			GPIOF,
			0x0B,
			{
					0x00, 0x01, 0x02,
					0x03, 0x04, 0x05,
					0x0B, 0x0C, 0x0D,
					0x0E, 0x0F
			},
			{
					GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,
					GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,
					GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,
					GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF
			},
			{
					GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,
					GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,
					GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,
					GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP
			},
			{
					GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,
					GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,
					GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,
					GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH
			},
			{
					GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,
					GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,
					GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,
					GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD
			},
			{
					GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,
					GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,
					GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,
					GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12
			}
	},
	{
			GPIOG,
			0x06,
			{
					0x00, 0x01, 0x04,
					0x05, 0x08, 0x0F
			},
			{
					GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,
					GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF,GPIO_DRIVER_MODE_AF
			},
			{
					GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,
					GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP,GPIO_DRIVER_OUT_TYPE_PP

			},
			{
					GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,
					GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH,GPIO_DRIVER_SPEED_HIGH
			},
			{
					GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,
					GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD,GPIO_DRIVER_PUPD_NO_PUPD
			},
			{
					GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,
					GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12,GPIO_DRIVER_AF_OPT_12
			}
	}
};

GPIO_Driver_Setup_Type* GPIO_SETUP = GPIO_CONF_SETUP;

void GPIO_Driver_Lambda_function()
{
/*	static uint8 status = 0x00;

	if(status == 0x00)
	{
		GPIO_Driver_ClearPin(GPIO_DRIVER_PORTG,GPIO_DRIVER_PORTG_PIN13);
	}
	else
	{
		GPIO_Driver_SetPin(GPIO_DRIVER_PORTG,GPIO_DRIVER_PORTG_PIN13);
	}

	status = !status;*/
}
