/*
 * JOYSTICK_Module_Cfg.h
 *
 *  Created on: Sep 11, 2018
 *      Author: zsolt.balo
 */

#ifndef MODULES_HARDWARE_MODULES_BUTTON_MODULE_JOYSTICK_MODULE_JOYSTICK_MODULE_CFG_H_
#define MODULES_HARDWARE_MODULES_BUTTON_MODULE_JOYSTICK_MODULE_JOYSTICK_MODULE_CFG_H_

#include "JOYSTICK_Module.h"

#define JOYSTICK_MODULE_INSTANCE_NUM 						((uint32)0x01)

typedef enum
{
	JOYSTICK_MODULE_0
}
JOYSTICK_Module_Instances;

#endif /* MODULES_HARDWARE_MODULES_BUTTON_MODULE_JOYSTICK_MODULE_JOYSTICK_MODULE_CFG_H_ */
